# Pre-commit hooks for security scanning
repos:
  # Secret detection with Gitleaks
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks

  # Additional security checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: detect-private-key
      - id: check-merge-conflict
      
  # Node.js specific checks
  - repo: local
    hooks:
      - id: env-file-check
        name: Check for .env files
        entry: bash -c 'if git diff --cached --name-only | grep -E "\.(env|bak|backup|old)$"; then echo "❌ Environment files detected in commit!"; exit 1; fi'
        language: system
        stages: [commit]
        
      - id: api-key-check
        name: Check for API keys in staged files
        entry: bash -c 'if git diff --cached | grep -E "(sk-|AIza|sb_secret_|eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*)"; then echo "❌ Potential API keys detected in commit!"; exit 1; fi'
        language: system
        stages: [commit]
        
      - id: npm-audit
        name: NPM Security Audit
        entry: npm audit --audit-level high
        language: system
        stages: [push]
        pass_filenames: false